### ISSUE TITLE
add temperature logging

### ISSUE THREAD

**Issue by itdaniher** [analogdevicesinc/m1k-fw#1]
The AD7682 and SAM3U both have internal temperature measurement support. Registering device temperatures > 80degC is probably important for deployments in places without air conditioning.

**Comment by dbogdan** [comment]
I don't think that SAM3U has an internal temperature sensor, so the only option is AD7682.

**Comment by dbogdan** [comment]
Temperature reading feature was added: https://github.com/analogdevicesinc/m1k-fw/commit/c1e2b6c61bd5bd2f25f71a1c39f63987956d3fda
