### ISSUE TITLE
Dropped CH B samples in v2.10 and higher

### ISSUE THREAD

**Issue by damercer** [analogdevicesinc/m1k-fw#12]
I've been using v2.09 all along until recently. I'm seeing that the dropped samples in channel B issue has come back in versions 2.10 through 2.13. The sample is not lost every time but very often probably more than half the time. The lost sample is at number 382 ( starting at sample 0 )

I've now gone back to v2.09 on all my boards until this gets fixed.

Doug

**Comment by dbogdan** [comment]
It will be fixed in 2.14.

Thanks,
Dragos

**Comment by dbogdan** [comment]
The issue seems to be solved in v2.15. This version also contains support for the Rev F LEDs.

Dragos
