### ISSUE TITLE
Problem building firmware on Ubuntu 18.04

### ISSUE THREAD

**Issue by damercer** [analogdevicesinc/m1k-fw#22]
Hi Dragos:

I loaded VMware on this old Windows 7 64 bit ADI laptop I have and installed Ubuntu 18.04 on it. After installing the various prerequisites including what I think is the latest gcc-arm-none-eabi (using sudo apt install gcc-arm-none-eabi) I cloned m1k-fw master and did a sudo make flash. That seemed to work and produces a m1000.bin file (reads back as 2.16 as it should).
I then flashed that file to one of my Rev F boards. However when I run Alice I'm getting lots of dropped / bad samples (getting I data samples in the V data array) like the versions I build with the Windows tool chain.

What are you doing differently to get this to work properly?

Thanks

Doug

**Comment by damercer** [comment]
By the way, when I do a byte by byte compare of the m1000.bin (V2.16) on github master with the one I just made they have almost no places where they are the same. They are also different lengths, 16,356 bytes vs 16,084. So obviously built by different compilers?

Again, my question is how do I replicate your environment?

Doug

**Comment by dbogdan** [comment]
Hi Doug,

On Linux, I'm using the same CodeSourcery Toolchain. Once you have it on your Linux machine, Makefile can be updated similar to https://github.com/analogdevicesinc/m1k-fw/issues/20 .

Dragos

**Comment by damercer** [comment]
Hi:
Sorry but please be specific so as to limit any confusion on my part.
How do I put this CodeSourcery Toolchain on the Linux VM?
Please don't say "similar", exactly what has to change in Makefile and how?

Thanks
Doug

**Comment by dbogdan** [comment]
Doug,

Download and extract: https://sourcery.mentor.com/public/gnu_toolchain/arm-none-eabi/arm-2014.05-28-arm-none-eabi-i686-pc-linux-gnu.tar.bz2
Update the m1k-fw Makefile by setting the CROSS macro (you can do it anywhere before including asf/sam/utils/make/Makefile.sam.in). Your new line should look like:
     CROSS=/home/analog/workspace/tools/arm-2014.05/bin/arm-none-eabi-

By the way, do you use a 64 bit version of Ubuntu? If this is the case, some additional libraries might be required since the Toolchain was targeted for i686. Let me know.

Dragos

**Comment by damercer** [comment]
Hi:
I'm not a Linux user so I don't know much of the command line stuff. What is command used to "extract" the downloaded file? Where exactly should it be extracted to and how?
I think I set up a 64 bit version of Ubumtu 18.04 on VMware. That computer is not connected right now so I can't check any further details. Let me know of any other things that need to be loaded.
Thanks
Doug

**Comment by dbogdan** [comment]
/* Extract */
analog@ubuntu:~/Downloads$ tar xvf ./arm-2014.05-28-arm-none-eabi-i686-pc-linux-gnu.tar.bz2
arm-2014.05/arm-none-eabi/
...
arm-2014.05/share/doc/arm-arm-none-eabi/html/libm/ccos.html

/* Find the location */
analog@ubuntu:~/Downloads$ pwd
/home/analog/Downloads

/* export CROSS before running make */
analog@ubuntu:~/Downloads/m1k-fw$ export CROSS=/home/analog/Downloads/arm-2014.05/bin/arm-none-eabi-

/* or update the Makefile */
analog@ubuntu:~/Downloads/m1k-fw$ sed -i '/GIT_VERSION/a CROSS=/home/analog/Downloads/arm-2014.05/bin/arm-none-eabi-' Makefile

Dragos

**Comment by damercer** [comment]
I down loaded and extracted using tar inside /home/downloads.
looking in the file manager there seems to be a arm-2014.05 folder with things in it.
I changed the Make file in /home/m1k-fw like this:

[Makefile.zip](https://github.com/analogdevicesinc/m1k-fw/files/2829592/Makefile.zip)

Then from inside m1k-fw I do this and get an error:

doug@ubuntu:~/m1k-fw$ sudo make flash
rm -f *bin *elf *hex *lss *map *sym *.o *.d *.su
CC      build/src/main.o
make: /home/downloads/arm-2014.05/bin/arm-none-eabi-gcc: Command not found
make: *** [asf/sam/utils/make/Makefile.sam.in:406: build/src/main.o] Error 127

Any ideas?
Thanks
Doug

**Comment by dbogdan** [comment]
Something is definitely wrong in your path. The user name is missing (you should have something like /home/username/Downloads) and the name of the downloads folder most likely starts with an uppercase character (Downloads). Linux is a case sensitive operating system.

Dragos

**Comment by damercer** [comment]
OK, in a terminal screen I navigated to where the files were extracted and did a pwd:
/home/doug/Downloads/arm-2014.05/bin
I then cut and pasted this text letter for letter into the Make file adding the arm-none-eabi- to the end:
CROSS=/home/doug/Downloads/arm-2014.05/bin/arm-none-eabi-
And I'm still getting the same error message when I try make in the m1k-fw folder?
I'm not the best typist when using the terminal command line but I think I'm doing this right. (a major reason I don't like using Linux)
Still not the answer to the problem I think.
Thanks
Doug

**Comment by dbogdan** [comment]
The new path seems correct. Can you install lib32z1, lib32ncurses5 and try to run make again (sudo apt-get install lib32z1 lib32ncurses5)?
Thanks,
Dragos

**Comment by damercer** [comment]
Adding those libraries fixed building the firmware binary. Thanks.
I also flashed this new binary to an m1k board and this one now seems to function as well as the one in master (2.16). I'm not seeing any bad, skipped, dropped, missing samples in the data using ALICE.
So I have this version working like yours in Linux.
Would adding these libraries (if possible to do) to the Atmel Studio 7 tool on Windows fix that one as well? It would be great if that could be made to work as well.
Thanks again.
Doug

**Comment by dbogdan** [comment]
No, those libraries were required only because you are on a 64-bits machine where you want to run a 32-bits application (the Toolchain).
It's a little bit strange that you get a different result on Windows. Do you use the same 2014.05-28 version?
Thanks,
Dragos

**Comment by damercer** [comment]
I guess this is all resolved now. Please see my pull request #21 for the changes I'd like added to the firmware.
Thanks.
Doug

**Comment by F1r3Hydr4nt** [comment]
> Download and extract: https://sourcery.mentor.com/public/gnu_toolchain/arm-none-eabi/arm-2014.05-28-arm-none-eabi-i686-pc-linux-gnu.tar.bz2

> Dragos

Have you got that file? Could you share it if so, or anybody else for that matter?
