### ISSUE TITLE
test mode

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/m1k-fw#6]
It would be great if we could add a "test mode", where known data is sent.

This test data could be ramp, or fixed number (midscale, zero, full scale).

**Comment by radhermit** [comment]
I think this is done by @dbogdan now. He just needs to push it to a branch with the related testing firmware binary in the repo as the m1000.bin file and then I can add some semi-automated test support that flashes the test firmware and checks things in the pysmu test suite.

**Comment by dbogdan** [comment]
A dedicated testing branch was created: https://github.com/analogdevicesinc/m1k-fw/tree/test
